{
 "title": "Corona",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Total cases in India",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "total_cases_confirmed" }
   ]
  },
  {
   "title": "Total Deaths",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "total_cases_deceased" }
   ]
  },
  {
   "title": "Total Recoveries",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "total_cases_recovered" }
   ]
  },
  {
   "title": "Highest cases by state",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(total_cases_confirmed_by_state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Total cases by state",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "expr": "total_cases_confirmed_by_state", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "Total cases by state",
   "type": "graph",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "total_cases_confirmed_by_state", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "Total Cases in India",
   "type": "graph",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "total_cases_confirmed", "legendFormat": "India" }
   ]
  }
 ]
}